### ISSUE TITLE
Set Up Kanban board

### ISSUE THREAD

**Issue by looh16** [ishpaul777/vespa-clone-frontend#16]
**This project is made up of 3 people:**

1. [Nonhlanhla](https://github.com/29td)
2. [Ishpaul](https://github.com/ishpaul777)
3. [Langa](https://github.com/looh16)

**project link:**
[Kanban board](https://github.com/users/ishpaul777/projects/6)

![scream1](https://user-images.githubusercontent.com/21173712/206186691-cc0aafff-5acd-4c45-b042-fc6095e6d02b.png)

**Comment by mcrd25** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your board.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the current state of the Kanban Board at the time of review request which is seen as a requirement [here](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  


Good luck! 🎉 


Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.
